name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Thay thế bằng lệnh build của dự án

    - name: Deploy to server
      run: |
        # Thực hiện các bước triển khai, ví dụ: copy files, ssh vào server, v.v.
        ssh user@your-server 'cd /path/to/deploy && git pull origin main'

    - name: Clean up
      run: npm prune